# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIExample-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'AgoraRtcEngine_iOS', '4.2.3'
  # pod 'sdk', :path => 'sdk.podspec'

  
end

target 'Agora-ScreenShare-Extension-OC' do
  use_frameworks!
  # pod 'sdk', :path => 'sdk.podspec'
pod 'AgoraRtcEngine_iOS', '4.2.3'
end

target 'SimpleFilter' do
  use_frameworks!
      # pod 'sdk', :path => 'sdk.podspec'
   pod 'AgoraRtcEngine_iOS', '4.2.3'
end
