# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'APIExample' do
  use_frameworks!
  
  pod 'Floaty', '~> 4.2.0'
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'CocoaAsyncSocket', '7.6.5'
  pod 'ijkplayer', '~> 1.1.3'
  pod 'SwiftLint', '~> 0.53.0'
  pod 'AgoraRtcEngine_iOS', '4.3.1'
#  pod 'sdk', :path => 'sdk.podspec'
#    pod 'senseLib', :path => 'sense.podspec'
#    pod 'bytedEffect', :path => 'bytedEffect.podspec'
#     pod 'fuLib', :path => 'fu.podspec'
end

target 'Agora-ScreenShare-Extension' do
  use_frameworks!
#  pod 'sdk', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_iOS', '4.3.1'
end

target 'SimpleFilter' do
  use_frameworks!
#  pod 'sdk', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_iOS', '4.3.1'
end

pre_install do |installer|
#  system("sh .download_script.sh 4.3.1 true")
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      # fix Xcode version > 15.0 & cocoapods version < 1.13.0 
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
