platform :ios, '12.0'

#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

def common_pods
   # pod 'AgoraRtcEngine_iOS', '4.7.0'
   pod 'sdk', :path => 'sdk.podspec'
end
  
target 'APIExample' do
  use_frameworks!
  
  common_pods
  
  pod 'Floaty', '~> 4.2.0'
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'CocoaAsyncSocket', '7.6.5'
  # If you need to test the compatibility of SDK with the "AudioRouter" of the third-party player, you can use ijkplayer or MobileVLCKit
  #  pod 'ijkplayer', '~> 1.1.3'
  #  pod 'MobileVLCKit', '3.5.1'
#  pod 'SwiftLint', '~> 0.53.0'
  pod 'SnapKit', '~> 5.7.0'

  pod 'SenseLib', :path => 'sense.podspec'
  pod 'fuLib', :path => 'fu.podspec'
end

target 'Agora-ScreenShare-Extension' do
  use_frameworks!
  
  common_pods
end

target 'SimpleFilter' do
  use_frameworks!
  common_pods
end

pre_install do |installer|
#  system("sh .download_script.sh 4.7.0 true")
end

# Xcode 27 SDKs require iOS 15; retain each pod's default for older SDKs.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current = Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] || '12.0')
      minimum = [current, Gem::Version.new('15.0')].max.to_s
      %w[iphoneos27.* iphonesimulator27.*].each do |sdk|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET[sdk=#{sdk}]"] = minimum
      end
    end
  end
end
