# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'APIExample' do
  use_frameworks!
  
  pod 'Floaty', '~> 4.2.0'
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'CocoaAsyncSocket', '7.6.5'
# 如需测试SDK与三方播放器的”AudioRouter“兼容，可以使用ijkplayer或MobileVLCKit
#  pod 'ijkplayer', '~> 1.1.3'
#  pod 'MobileVLCKit', '3.5.1'
  pod 'SwiftLint', '~> 0.53.0'
  pod 'AgoraRtcEngine_iOS', '4.4.0'
#  pod 'sdk', :path => 'sdk.podspec'
#    pod 'senseLib', :path => 'sense.podspec'
#    pod 'bytedEffect', :path => 'bytedEffect.podspec'
#     pod 'fuLib', :path => 'fu.podspec'
end

target 'Agora-ScreenShare-Extension' do
  use_frameworks!
#  pod 'sdk', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_iOS', '4.4.0'
end

target 'SimpleFilter' do
  use_frameworks!
#  pod 'sdk', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_iOS', '4.4.0'
end

pre_install do |installer|
#  system("sh .download_script.sh 4.4.0 true")
end
