//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 APIExample.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_APIEXAMPLE_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LIVEBROADCASTING     130
#define IDD_DIALOG_RTMPINJECT           131
#define IDD_DIALOG_RTMP_STREAMING       132
#define IDD_DIALOG_METADATA             133
#define IDD_DIALOG_SCREEN_SHARE         134
#define IDD_DIALOG_CUSTOM_CAPTURE_VIDEO 135
#define IDD_DIALOG_CUSTOM_CAPTURE_AUDIO 136
#define IDD_DIALOG_BEAUTY               137
#define IDD_DIALOG_AUDIO_PROFILE        138
#define IDD_DIALOG_BEAUTY_AUDIO         139
#define IDD_DIALOG_AUDIO_MIX            140
#define IDD_DIALOG_ORIGINAL_VIDEO       141
#define IDD_DIALOG_ORIGINAL_AUDIO       142
#define IDC_BUTTON_FAQ                  1000
#define IDC_BUTTON_DOCUMENT2            1001
#define IDC_BUTTON_DOCUMENT_WEBSITE     1001
#define IDC_BUTTON_DEMO                 1002
#define IDC_LIST_BASIC                  1003
#define IDC_BUTTON_REGISTER             1004
#define IDC_LIST_ADVANCED               1005
#define IDC_STATIC_GROUP_DOC            1006
#define IDC_STATIC_MAIN                 1008
#define IDC_STATIC_ADVANCED             1009
#define IDC_STATIC_VIDEO                1010
#define IDC_LIST_INFO_BROADCASTING      1011
#define IDC_COMBO_ROLE                  1015
#define IDC_COMBO_ROLE2                 1016
#define IDC_COMBO_PERSONS               1016
#define IDC_STATIC_ROLE                 1017
#define IDC_STATIC_PERSONS              1018
#define IDC_STATIC_CHANNELNAME          1019
#define IDC_EDIT_CHANNELNAME            1020
#define IDC_BUTTON1                     1021
#define IDC_BUTTON_JOINCHANNEL          1021
#define IDC_STATIC_INJECT_URL           1022
#define IDC_STATIC_SENDSEI              1022
#define IDC_EDIT_LIGHTENING             1022
#define IDC_EDIT_AUDIO_MIX_PATH         1022
#define IDC_EDIT_INJECT_URL             1023
#define IDC_EDIT_SEI                    1023
#define IDC_EDIT_BEAUTY_REDNESS         1023
#define IDC_EDIT_AUDIO_REPEAT_TIMES     1023
#define IDC_BUTTON_ADDSTREAM            1024
#define IDC_BUTTON_SEND                 1024
#define IDC_EDIT_BEAUTY_SMOOTHNESS      1024
#define IDC_BUTTON_REMOVE_STREAM        1025
#define IDC_EDIT_RECV                   1025
#define IDC_BUTTON_REMOVE_ALLSTREAM     1026
#define IDC_STATIC_RTMP_URL             1030
#define IDC_EDIT_RTMP_URL               1031
#define IDC_STATIC_RTMP_URLS            1032
#define IDC_COMBO_RTMPURLS              1033
#define IDC_STATIC_ADVANCE              1034
#define IDC_STATIC_LIST_INFO            1035
#define IDC_STATIC_GROUP_LIST           1037
#define IDC_STATIC_DETAIL               1038
#define IDC_STATIC_METADATA_INFO        1039
#define IDC_BUTTON_CLEAR                1040
#define IDC_STATIC_SCREEN_CAPTURE       1041
#define IDC_COMBO_SCREEN_CAPTURE        1042
#define IDC_BUTTON_START_CAPUTRE        1043
#define IDC_STATIC_CAPTUREDEVICE        1044
#define IDC_STATIC_BEAUTY_LIGHTENING    1044
#define IDC_COMBO_CAPTURE_VIDEO_DEVICE  1045
#define IDC_COMBO_CAPTURE_TYPE          1046
#define IDC_COMBO_CAPTURE_VIDEO_TYPE    1046
#define IDC_COMBO_CAPTURE_AUDIO_DEVICE  1047
#define IDC_COMBO_CAPTURE_AUDIO_TYPE    1048
#define IDC_STATIC_BEAUTY_LIGHTENING_CONTRAST_LEVEL 1049
#define IDC_COMBO_BEAUTE_LIGHTENING_CONTRAST_LEVEL 1050
#define IDC_STATIC_BEAUTY_REDNESS       1051
#define IDC_STATIC_BEAUTY_SMOOTHNESS    1052
#define IDC_CHECK1                      1054
#define IDC_CHECK_BEAUTY_ENABLE         1054
#define IDC_CHK_ONLY_LOCAL              1054
#define IDC_STATIC_ADUIO_PROFILE        1055
#define IDC_CHK_REPLACE_MICROPHONE      1055
#define IDC_STATIC_ADUIO_SCENARIO       1056
#define IDC_COMBO_AUDIO_PROFILE         1057
#define IDC_COMBO_AUDIO_SCENARIO        1058
#define IDC_BUTTON_SET_AUDIO_PROFILE    1059
#define IDC_STATIC_AUDIO_CHANGER        1060
#define IDC_COMBO_AUDIO_CHANGER         1061
#define IDC_BUTTON_SET_AUDIO_CHANGE     1062
#define IDC_STATIC_AUDIO_MIX            1063
#define IDC_BUTTON_SET_AUDIO_MIX        1064
#define IDC_STATIC_AUDIO_REPEAT         1065
#define IDC_STATIC_ORIGINAL_VIDEO_PROC  1065
#define IDC_COMBO_ORIGINAL_VIDEO_PROC   1066
#define IDC_BUTTON_SET_ORIGINAL_PROC    1067
#define IDC_STATIC_ORIGINAL_AUDIO_PROC  1068
#define IDC_COMBO_ORIGINAL_AUDIO_PROC   1069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
