macos_deployment_target = '12.0'
platform :osx, macos_deployment_target


def common_pods
   pod 'AgoraRtcEngine_macOS', '4.7.0'
  # pod 'sdk', :path => 'sdk.podspec'
end

target 'APIExample' do
  use_frameworks!
  
  common_pods

  pod 'AGEVideoLayout', '1.0.2'
end

target 'SimpleFilter' do
  use_frameworks!
  common_pods
end


post_install do |installer|
  # system("sh .download_script.sh 4.7.0 true")
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      deployment_target = config.build_settings['MACOSX_DEPLOYMENT_TARGET']
      if deployment_target.nil? || Gem::Version.new(deployment_target) < Gem::Version.new(macos_deployment_target)
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = macos_deployment_target
      end
    end
  end
end
