# Uncomment the next line to define a global platform for your project

target 'APIExample' do
  use_frameworks!

  pod 'AGEVideoLayout', '1.0.2'
  pod 'AgoraRtcEngine_macOS', '4.2.0'
#   pod 'sdk', :path => 'sdk.podspec'
end

target 'SimpleFilter' do
  use_frameworks!
#   pod 'sdk', :path => 'sdk.podspec'
  pod 'AgoraRtcEngine_macOS', '4.2.1'
end
