# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''  
  sdkVersion: ''
  faceUnitySDKVersion: ''
  Machine: ''
  solutionName: ''
  release: ''
jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'windows-2019'

    variables:
      - group: AgoraKeys
      - name: solution
        value: '${{ parameters.workingDirectory }}/${{ parameters.solutionName }}'
      - name: buildPlatform
        value: '${{ parameters.Machine }}'
      - name: buildConfiguration
        value: 'Release'
      - name: WindowsRTCSDK
        value: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_v${{ parameters.sdkVersion }}_FULL.zip'
      - name: Windows-ThirdParty
        value: 'https://github.com/AgoraIO/Advanced-Video/releases/download/Dshow/ThirdParty.zip'
      - name: sdkunzipPath
        value: 'AgoraSDK/Agora_Native_SDK_for_Windows_FULL'
      - name: MediaPlayer
        value: 'https://download.agora.io/sdk/release/Agora_Media_Player_for_Windows_x86_rel.v1.1.0.16486_20200507_1537.zip'
    steps:
      - script: echo "$(WindowsRTCSDK)" && ls
      #AgoraSDK
      - powershell: Windows/cicd/script/downloadsdk1.ps1 "$(WindowsRTCSDK)" "AgoraSDK.zip"
      #ThirdParty
      - powershell: Windows/cicd/script/downloadsdk1.ps1 "$(Windows-ThirdParty)" "ThirdParty.zip"
      #MediaPlayer
      - powershell: Windows/cicd/script/downloadsdk1.ps1 "$(MediaPlayer)" "MediaPlayer.zip"
      - script: cd ${{ parameters.workingDirectory }} && ls && python ci.py
        env:
          AGORA_APP_ID: $(agora.appId)
          
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'AgoraSDK.zip' 
          destinationFolder: 'AgoraSDK'    
          
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'ThirdParty.zip' 
          destinationFolder: 'ThirdParty' 
          
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'MediaPlayer.zip' 
          destinationFolder: 'MediaPlayer'    
      
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'ThirdParty/DShow'
          targetFolder: ${{ parameters.workingDirectory }}/ThirdParty/DShow
      
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'ThirdParty/libyuv'
          targetFolder: ${{ parameters.workingDirectory }}/ThirdParty/libyuv
      
      - task: CopyFiles@2
        inputs:
            sourceFolder: 'MediaPlayer/Agora_Media_Player_for_Windows_x86_rel.v1.1.0.16486_20200507_1537/sdk/include'
            targetFolder: ${{ parameters.workingDirectory }}/MediaPlayerPart/include
      - task: CopyFiles@2
        inputs:
            sourceFolder: 'MediaPlayer/Agora_Media_Player_for_Windows_x86_rel.v1.1.0.16486_20200507_1537/sdk/lib'
            targetFolder: ${{ parameters.workingDirectory }}/MediaPlayerPart/lib
      - task: CopyFiles@2
        inputs:
            sourceFolder: 'MediaPlayer/Agora_Media_Player_for_Windows_x86_rel.v1.1.0.16486_20200507_1537/sdk/dll'
            targetFolder: ${{ parameters.workingDirectory }}/MediaPlayerPart/dll            
            
      - script: ls
      
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(sdkunzipPath)/libs
          targetFolder: ${{ parameters.workingDirectory }}/libs
          
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          vsVersion: '15.0'
          msbuildArchitecture: '${{ parameters.Machine }}'
      - script: cd ${{ parameters.workingDirectory }}/${{ parameters.release }} && ls
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: ${{ parameters.workingDirectory }}/${{ parameters.release }}
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          ArtifactName: ${{ parameters.displayName }}
      
