# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''  
  sdkVersion: ''
  faceUnitySDKVersion: ''
  Machine: ''
  solutionName: ''
  release: ''
jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'vs2017-win2016'

    variables:
      solution: '${{ parameters.workingDirectory }}/${{ parameters.solutionName }}'
      buildPlatform: '${{ parameters.Machine }}'
      buildConfiguration: 'Release'
      WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_v${{ parameters.sdkVersion }}_FULL.zip'
      Windows-ThirdParty: 'https://github.com/AgoraIO/Advanced-Video/releases/download/Dshow/ThirdParty.zip'
      sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_FULL'
    steps:
      - script: echo "$(WindowsRTCSDK)" && ls
      #AgoraSDK
      - powershell: Windows/cicd/script/downloadsdk1.ps1 "$(WindowsRTCSDK)" "AgoraSDK.zip"
      #ThirdParty
      - powershell: Windows/cicd/script/downloadsdk1.ps1 "$(Windows-ThirdParty)" "ThirdParty.zip"
      
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'AgoraSDK.zip' 
          destinationFolder: 'AgoraSDK'    
          
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'ThirdParty.zip' 
          destinationFolder: 'ThirdParty'    
          
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'ThirdParty/DShow'
          targetFolder: ${{ parameters.workingDirectory }}/ThirdParty/DShow
      
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'ThirdParty/libyuv'
          targetFolder: ${{ parameters.workingDirectory }}/ThirdParty/libyuv
      - script: ls
          
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(sdkunzipPath)/libs
          targetFolder: ${{ parameters.workingDirectory }}/libs

      - script: cd ${{ parameters.workingDirectory }} && ls
      - script: ls       
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          vsVersion: '15.0'
          msbuildArchitecture: '${{ parameters.Machine }}'
      - script: cd ${{ parameters.workingDirectory }}/${{ parameters.release }} && ls
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: ${{ parameters.workingDirectory }}/${{ parameters.release }}
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/${{ parameters.displayName }}.zip
          ArtifactName: ${{ parameters.displayName }}
      
