# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIExample' do
  use_frameworks!
  
  pod 'Floaty', '~> 4.2.0'
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'CocoaAsyncSocket', '7.6.5'
  pod 'AgoraRtcEngine_iOS_Beta', '4.0.0-beta.2'
end

target 'Agora-ScreenShare-Extension' do
  use_frameworks!
  
  pod 'AgoraRtcEngine_iOS_Beta', '4.0.0-beta.2'
end

target 'SimpleFilter' do
  use_frameworks!
  
  pod 'AgoraRtcEngine_iOS_Beta', '4.0.0-beta.2'
end
