# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIExample' do
  
  use_frameworks!
  
  pod 'AGEVideoLayout', '~> 1.0.2'
  # use this if you don't need encryption feature
  # pod 'AgoraRtcEngine_iOS', '~> 3.1.1'
  #pod 'AgoraRtcEngine_iOS_Crypto', '~> 3.1.1'
  #pod 'AgoraMediaPlayer_iOS', '1.1.4'
end

target 'Agora-ScreenShare-Extension' do

  use_frameworks!

  # use this if you don't need encryption feature
  # pod 'AgoraRtcEngine_iOS', '~> 3.1.1'
  #pod 'AgoraRtcEngine_iOS_Crypto', '~> 3.1.1'
end
