

// Agora APP ID.
// 声网APP ID。
export const AppID: string = 'c835edada0f845d5baf91bf4a9dd12a2'

// Agora APP Certificate. If the project does not have certificates enabled, leave this field blank.
// PS：It is unsafe to place the App Certificate on the client side, it is recommended to place it on the server side to ensure that the App Certificate is not leaked.
// 声网APP证书。如果项目没有开启证书鉴权，这个字段留空。
// 注意：App证书放在客户端不安全，推荐放在服务端以确保 App 证书不会泄露。
export const AppCertificate: string = ''