// Controlled SDK/UI doubles. The NetworkManager interface is generated by Swift separately.
#import <Foundation/Foundation.h>
@protocol AgoraRtcEngineDelegate <NSObject> @end
typedef NSInteger AgoraErrorCode;
typedef NS_ENUM(NSInteger, AgoraClientRole) { AgoraClientRoleBroadcaster = 1 };
@interface UIViewController : NSObject
- (void)viewDidLoad;
- (void)willMoveToParentViewController:(UIViewController *)parent;
@end
@implementation UIViewController
- (void)viewDidLoad {}
- (void)willMoveToParentViewController:(UIViewController *)parent {}
@end
@interface BaseViewController : UIViewController @end
@implementation BaseViewController @end
@interface TemplateMain : BaseViewController @end
@interface AgoraRtcEngineConfig : NSObject
@property NSString *appId;
@end
@implementation AgoraRtcEngineConfig @end
@interface AgoraRtcChannelMediaOptions : NSObject
@property AgoraClientRole clientRoleType;
@property BOOL publishMicrophoneTrack;
@end
@implementation AgoraRtcChannelMediaOptions @end
static NSMutableArray *engines;
static int destroys, joins, joinResult;
static NSString *lastChannel;
static NSUInteger lastUID;
@interface AgoraRtcEngineKit : NSObject
@property BOOL destroyed;
@property int leaves;
+ (instancetype)sharedEngineWithConfig:(AgoraRtcEngineConfig *)config delegate:(id)delegate;
+ (void)destroy;
- (int)leaveChannel:(id)completion;
- (int)joinChannelByToken:(NSString *)token channelId:(NSString *)channel uid:(NSUInteger)uid
            mediaOptions:(AgoraRtcChannelMediaOptions *)options joinSuccess:(id)completion;
@end
@implementation AgoraRtcEngineKit
+ (instancetype)sharedEngineWithConfig:(AgoraRtcEngineConfig *)config delegate:(id)delegate {
    if (!engines) engines = [NSMutableArray new];
    AgoraRtcEngineKit *engine = [self new];
    [engines addObject:engine];
    return engine;
}
+ (void)destroy { destroys++; ((AgoraRtcEngineKit *)engines.lastObject).destroyed = YES; }
- (int)leaveChannel:(id)completion { assert(!self.destroyed); self.leaves++; return 0; }
- (int)joinChannelByToken:(NSString *)token channelId:(NSString *)channel uid:(NSUInteger)uid
            mediaOptions:(AgoraRtcChannelMediaOptions *)options joinSuccess:(id)completion {
    assert([NSThread isMainThread] && !self.destroyed);
    joins++; lastChannel = channel; lastUID = uid;
    return joinResult;
}
@end
static NSString *certificate;
@interface KeyCenter : NSObject
+ (NSString *)AppId;
+ (NSString *)Certificate;
@end
@implementation KeyCenter
+ (NSString *)AppId { return @""; }
+ (NSString *)Certificate { return certificate; }
@end
