#!/usr/bin/env python3
"""Add complete template smoke sources to a disposable Compile CI checkout.

This deliberately edits the checkout (and Xcode target membership). Do not run in a working
copy containing user edits. No SDK/configuration/credentials are generated by this helper.
"""
import argparse
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[3]
PROJECTS = (
    "Android/APIExample-Audio", "Android/APIExample-Compose",
    "iOS/APIExample", "iOS/APIExample-Audio", "iOS/APIExample-SwiftUI", "iOS/APIExample-OC",
)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", choices=PROJECTS)
    args = parser.parse_args()
    project = ROOT / args.project
    skill = project / ".agents/skills/upsert-case"
    if args.project.startswith("Android/"):
        audio = args.project.endswith("Audio")
        template = skill / "references" / ("fragment-template.java" if audio else "composable-template.kt")
        name = "AudioExampleCaseTemplate.java" if audio else "AITemplateSmoke.kt"
        destination = project / "app/src/main/java/ai/templatecheck" / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("x") as target:
            target.write(template.read_text())
    else:
        source = (skill / "SKILL.md").read_text()
        if args.project.endswith("OC"):
            blocks = re.findall(r"```objc\n(.*?)\n```", source, re.S)
            files = {"AITemplateSmoke.h": blocks[0], "AITemplateSmoke.m": blocks[1]}
        else:
            blocks = re.findall(r"```swift\n(.*?)\n```", source, re.S)
            count = 2 if args.project.endswith("SwiftUI") else 1
            files = {"AITemplateSmoke.swift": "\n".join(blocks[:count])}
        for name, content in files.items():
            with (project / name).open("x") as target:
                target.write(content.replace("<ExampleName>", "AITemplateSmoke"))
        # CocoaPods supplies xcodeproj. Compile the smoke source in the actual application target
        # so SDK, UIKit/SwiftUI and the generated Swift-to-OC header come from that project.
        subprocess.run([
            "ruby", "-rxcodeproj", "-e", """
project = Xcodeproj::Project.open(ARGV.shift)
name = ARGV.shift
target = project.targets.find { |item| item.name == name }
abort("Missing application target #{name}") unless target
ARGV.each do |path|
  reference = project.main_group.new_file(path)
  target.source_build_phase.add_file_reference(reference) unless path.end_with?('.h')
end
project.save
""", str(project / (project.name + ".xcodeproj")), project.name, *files,
        ], check=True, timeout=60)
    print(f"Staged complete template for {args.project}; run its normal compile command next.")


if __name__ == "__main__":
    main()
