# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'AgoraRtcEngine_iOS', '4.5.0'
#  pod 'sdk', :path => 'sdk.podspec'
end

target 'APIExample-SwiftUI' do
  use_frameworks!
    
  common_pods
  
#  pod 'CocoaAsyncSocket', '7.6.5'
#  pod 'ijkplayer', '~> 1.1.3'
#  pod 'SwiftLint', '~> 0.53.0'
#    pod 'senseLib', :path => 'sense.podspec'
#    pod 'bytedEffect', :path => 'bytedEffect.podspec'
#     pod 'fuLib', :path => 'fu.podspec'

end

target 'Agora-ScreenShare-Extension' do
  use_frameworks!
      
  common_pods
end

#target 'SimpleFilter' do
#  use_frameworks!
    
#  common_pods
#end

pre_install do |installer|
#  system("sh .download_script.sh 4.3.0 true")
end
